### ISSUE TITLE
cannot release priority array

### ISSUE THREAD

**Issue by jli113** [REQUEA/bacnet#1]
I have successfully written values into priority 8, but when using TypeReal and nil to release priority, I got the following error.

panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.typeSlow({0x0?, 0x0?, 0xc000110001?})
        C:/Program Files/Go/src/reflect/value.go:2610 +0x12e
reflect.Value.Type(...)
        C:/Program Files/Go/src/reflect/value.go:2605
github.com/jli113/gobacnet/internal/encoding.(*Encoder).ContextAsbtractType(0xc00011f848, 0x3, {0x48?, {0x0?, 0x0?}})
        D:/BACnet_Stack/gobacnet/internal/encoding/encoding.go:314 +0x5bc
github.com/jli113/gobacnet/bacip.WriteProperty.MarshalBinary({{0x2, 0x1}, {0x55, 0xc0000964cc}, {0x4, {0x0, 0x0}}, 0x8})
        D:/BACnet_Stack/gobacnet/bacip/services.go:120 +0xc5
github.com/jli113/gobacnet/bacip.APDU.MarshalBinary({0x0, 0xf, {0x11f28d0, 0xc000092300}, 0x0, 0x0, 0x0, 0x0})
        D:/BACnet_Stack/gobacnet/bacip/network_types.go:288 +0xa9
github.com/jli113/gobacnet/bacip.NPDU.MarshalBinary({0x1, 0x0, 0x1, 0x0, 0xc00011fd40, 0xc000092340, 0xff, 0x0, 0x0, 0xc00011fc78})
        D:/BACnet_Stack/gobacnet/bacip/network_types.go:89 +0x3c9
github.com/jli113/gobacnet/bacip.BVLC.MarshalBinary({0x81, 0xa, {0x1, 0x0, 0x1, 0x0, 0xc00011fd40, 0xc000092340, 0xff, 0x0, ...}})
        D:/BACnet_Stack/gobacnet/bacip/network_types.go:377 +0x6a
github.com/jli113/gobacnet/bacip.(*Client).send(0xc0000b8000, {0x1, 0x0, 0x1, 0x0, 0xc00011fd40, 0xc000092340, 0xff, 0x0, 0x0, ...})
        D:/BACnet_Stack/gobacnet/bacip/client.go:395 +0xae
github.com/jli113/gobacnet/bacip.(*Client).WriteProperty(0xc0000b8000, {0x11f2d00, 0xc000098450}, {{0x8, 0xbb7}, 0x5c4, 0x0, 0x220, {{0xc0000964a0, 0x6, ...}, ...}}, ...)
        D:/BACnet_Stack/gobacnet/bacip/client.go:369 +0x2e7
github.com/jli113/gobacnet/bacapp.WritePropertyValue(0xbb7?, {{0x8, 0xbb7}, 0x5c4, 0x0, 0x220, {{0xc0000964a0, 0x6, 0x6}, 0x0, ...}}, ...)        
        D:/BACnet_Stack/gobacnet/bacapp/bacapp.go:271 +0x1ba
main.main()
        D:/BACnet_Stack/gobacnet/main/main.go:66 +0x13a
exit status 2

When using typrnull and value of nil, the error is context deadline exceeded

**Comment by jli113** [comment]
nothing wrong with the code, the local bacnet was too busy to respond.
